package dev.chaosutils.gui;

import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.resources.Identifier;

import dev.chaosutils.util.Render;

/**
 * Vector icon set of the ChaosUtils interface.
 *
 * <p>The glyphs live in a single, white-on-transparent atlas so they can be tinted with the
 * current accent colour at draw time. The sheet is generated by {@code tools/make_ui_icons.py}
 * from signed distance functions, which keeps the strokes smooth at every GUI scale instead of
 * looking like upscaled pixels.
 *
 * <p>Drawing an icon is a single blit - no geometry is built per frame, so the cost is the same
 * as drawing a vanilla sprite.
 */
public enum UiIcons {
	LAYERS,
	EYE,
	RADIAL,
	CHAT,
	BOX,
	NOTE,
	SPARKLE,
	GAUGE,
	SLIDERS,
	PALETTE,
	FOLDER,
	USERS,
	KEYBOARD,
	SEARCH,
	ZOOM,
	LIST,
	GRID,
	CHEVRON,
	CHEVRON_DOWN,
	CHEVRON_LEFT,
	CHEVRON_UP,
	CHECK,
	CLOSE,
	PLUS,
	MINUS,
	TRASH,
	PENCIL,
	COPY,
	REFRESH,
	ARROW_UP,
	ARROW_DOWN,
	DRAG,
	LOCK,
	UNLOCK,
	EYE_OFF,
	LINK,
	INFO,
	WARN,
	CLOCK,
	PIN,
	CAMERA,
	BELL,
	SHIELD,
	HOME,
	SUN,
	CROSSHAIR,
	PARTICLES,
	PERSON,
	SCREENSHOT,
	STAR,
	DOT,
	SERVER,
	VOLUME,
	FILTER,
	SORT,
	COMPASS,
	DOWNLOAD,
	UPLOAD;

	/** Cell size of the atlas in pixels - also the native size of every glyph. */
	public static final int CELL = 20;
	/** Cells per row in the atlas. */
	public static final int COLUMNS = 11;

	private static final Identifier ATLAS = Identifier.fromNamespaceAndPath("chaosutils", "textures/gui/icons.png");

	/** Height of the atlas in pixels; used for the V coordinate. */
	private static int atlasHeight = CELL * 6;

	/** Set once the atlas could not be found, so the interface can degrade quietly. */
	private static boolean unavailable;
	private static boolean logged;

	private UiIcons() {
	}

	/** Draws the icon inside the box {@code (x, y, size, size)}. */
	public void draw(GuiGraphics graphics, float x, float y, float size, int color) {
		draw(graphics, x, y, size, size, color);
	}

	/** Draws the icon stretched into the given box. */
	public void draw(GuiGraphics graphics, float x, float y, float width, float height, int color) {
		if (unavailable || Render.alphaOf(color) == 0) {
			return;
		}
		int x0 = Math.round(x);
		int y0 = Math.round(y);
		int x1 = Math.round(x + width);
		int y1 = Math.round(y + height);
		if (x1 - x0 < 1 || y1 - y0 < 1) {
			return;
		}
		int index = ordinal();
		float u = (index % COLUMNS) * CELL;
		float v = (index / COLUMNS) * CELL;
		try {
			graphics.blit(RenderPipelines.GUI_TEXTURED, ATLAS, x0, y0, u, v, x1 - x0, y1 - y0, CELL, CELL,
					COLUMNS * CELL, atlasHeight, color);
		} catch (Throwable throwable) {
			unavailable = true;
			if (!logged) {
				logged = true;
				dev.chaosutils.ChaosUtils.LOGGER.warn("ChaosUtils icon atlas missing, falling back to shapes", throwable);
			}
		}
	}

	/** Draws the icon centred on the given point. */
	public void drawCentered(GuiGraphics graphics, float centerX, float centerY, float size, int color) {
		draw(graphics, centerX - size * 0.5F, centerY - size * 0.5F, size, size, color);
	}

	/**
	 * Draws the icon with a soft halo behind it - used for the selected sidebar entry and the
	 * big module icons of the detail panel. The halo is a single soft-edged quad.
	 */
	public void drawGlowing(GuiGraphics graphics, float centerX, float centerY, float size, int color, float glow) {
		if (glow > 0.01F) {
			float spread = size * (0.35F + 0.45F * glow);
			Render.halo(graphics, centerX - spread, centerY - spread, spread * 2.0F, spread * 2.0F,
					spread, color, glow * 0.45F);
		}
		drawCentered(graphics, centerX, centerY, size, color);
	}

	/** True when the atlas is present; the caller can then prefer icons over text markers. */
	public static boolean available() {
		return !unavailable;
	}
}
